# Generated by Django 2.2.1 on 2019-06-06 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksystem', '0005_auto_20170404_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seat_type',
            field=models.CharField(choices=[('头等舱', '头等舱'), ('公务舱', '公务舱'), ('经济舱', '经济舱')], default='经济舱', max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fetch', models.BooleanField(default=False)),
                ('is_refund', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
