# Generated by Django 2.2.1 on 2019-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0007_auto_20190606_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_fetch',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_refund',
            field=models.BooleanField(null=True),
        ),
    ]
