# Generated by Django 2.2.1 on 2019-06-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0008_auto_20190606_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
